// <auto-generated />
using System;
using Core.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Location.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PttCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Domain.Entities.Location.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Iso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Domain.Entities.Location.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("Domain.Entities.Personal.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Entities.Personal.UserContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserContacts");
                });

            modelBuilder.Entity("Domain.Entities.Personal.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("SettingsId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SettingsId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("Domain.Entities.System.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("Domain.Entities.System.MessageUs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MessageUsReasonId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MessageUsReasonId");

                    b.ToTable("MessageUs");
                });

            modelBuilder.Entity("Domain.Entities.System.MessageUsReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MessageUsReasons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(8497),
                            IsDeleted = false,
                            Name = "Info"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(8510),
                            IsDeleted = false,
                            Name = "Order"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(8514),
                            IsDeleted = false,
                            Name = "Complain"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(8518),
                            IsDeleted = false,
                            Name = "Suggest"
                        });
                });

            modelBuilder.Entity("Domain.Entities.System.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DarkMode")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("StickyNavBar")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Domain.Entities.System.SocialMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SocialMedia");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "FACEBOOK",
                            Color = "#1877F2",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(8300),
                            DisplayOrder = 1,
                            Icon = "facebook.svg",
                            IsDeleted = false,
                            Name = "Facebook"
                        },
                        new
                        {
                            Id = 2,
                            Code = "INSTAGRAM",
                            Color = "#E4405F",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(8314),
                            DisplayOrder = 2,
                            Icon = "instagram.svg",
                            IsDeleted = false,
                            Name = "Instagram"
                        },
                        new
                        {
                            Id = 3,
                            Code = "LINKEDIN",
                            Color = "#0A66C2",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(8319),
                            DisplayOrder = 3,
                            Icon = "linkedin.svg",
                            IsDeleted = false,
                            Name = "LinkedIn"
                        },
                        new
                        {
                            Id = 4,
                            Code = "X",
                            Color = "#000000",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(8325),
                            DisplayOrder = 4,
                            Icon = "x.svg",
                            IsDeleted = false,
                            Name = "X"
                        },
                        new
                        {
                            Id = 5,
                            Code = "YOUTUBE",
                            Color = "#FF0000",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(8329),
                            DisplayOrder = 5,
                            Icon = "youtube.svg",
                            IsDeleted = false,
                            Name = "YouTube"
                        },
                        new
                        {
                            Id = 6,
                            Code = "TIKTOK",
                            Color = "#000000",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(8334),
                            DisplayOrder = 6,
                            Icon = "tiktok.svg",
                            IsDeleted = false,
                            Name = "TikTok"
                        },
                        new
                        {
                            Id = 7,
                            Code = "WHATSAPP",
                            Color = "#25D366",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(8338),
                            DisplayOrder = 7,
                            Icon = "whatsapp.svg",
                            IsDeleted = false,
                            Name = "WhatsApp"
                        },
                        new
                        {
                            Id = 8,
                            Code = "TELEGRAM",
                            Color = "#26A5E4",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(8342),
                            DisplayOrder = 8,
                            Icon = "telegram.svg",
                            IsDeleted = false,
                            Name = "Telegram"
                        },
                        new
                        {
                            Id = 9,
                            Code = "DISCORD",
                            Color = "#5865F2",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(8346),
                            DisplayOrder = 9,
                            Icon = "discord.svg",
                            IsDeleted = false,
                            Name = "Discord"
                        },
                        new
                        {
                            Id = 10,
                            Code = "GITHUB",
                            Color = "#181717",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(8350),
                            DisplayOrder = 10,
                            Icon = "github.svg",
                            IsDeleted = false,
                            Name = "GitHub"
                        },
                        new
                        {
                            Id = 11,
                            Code = "GITLAB",
                            Color = "#FC6D26",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(8355),
                            DisplayOrder = 11,
                            Icon = "gitlab.svg",
                            IsDeleted = false,
                            Name = "GitLab"
                        },
                        new
                        {
                            Id = 12,
                            Code = "PINTEREST",
                            Color = "#E60023",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(8359),
                            DisplayOrder = 12,
                            Icon = "pinterest.svg",
                            IsDeleted = false,
                            Name = "Pinterest"
                        },
                        new
                        {
                            Id = 13,
                            Code = "SNAPCHAT",
                            Color = "#FFFC00",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(8363),
                            DisplayOrder = 13,
                            Icon = "snapchat.svg",
                            IsDeleted = false,
                            Name = "Snapchat"
                        },
                        new
                        {
                            Id = 14,
                            Code = "DRIBBBLE",
                            Color = "#EA4C89",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(8368),
                            DisplayOrder = 14,
                            Icon = "dribbble.svg",
                            IsDeleted = false,
                            Name = "Dribbble"
                        },
                        new
                        {
                            Id = 15,
                            Code = "BEHANCE",
                            Color = "#1769FF",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(8373),
                            DisplayOrder = 15,
                            Icon = "behance.svg",
                            IsDeleted = false,
                            Name = "Behance"
                        },
                        new
                        {
                            Id = 16,
                            Code = "MEDIUM",
                            Color = "#000000",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(8378),
                            DisplayOrder = 16,
                            Icon = "medium.svg",
                            IsDeleted = false,
                            Name = "Medium"
                        },
                        new
                        {
                            Id = 17,
                            Code = "REDDIT",
                            Color = "#FF4500",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(8382),
                            DisplayOrder = 17,
                            Icon = "reddit.svg",
                            IsDeleted = false,
                            Name = "Reddit"
                        },
                        new
                        {
                            Id = 18,
                            Code = "TWITCH",
                            Color = "#9146FF",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(8387),
                            DisplayOrder = 18,
                            Icon = "twitch.svg",
                            IsDeleted = false,
                            Name = "Twitch"
                        },
                        new
                        {
                            Id = 19,
                            Code = "SPOTIFY",
                            Color = "#1DB954",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(8391),
                            DisplayOrder = 19,
                            Icon = "spotify.svg",
                            IsDeleted = false,
                            Name = "Spotify"
                        },
                        new
                        {
                            Id = 20,
                            Code = "THREADS",
                            Color = "#000000",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(8396),
                            DisplayOrder = 20,
                            Icon = "threads.svg",
                            IsDeleted = false,
                            Name = "Threads"
                        });
                });

            modelBuilder.Entity("Domain.Entities.WebSiteBuilder.BusinessType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BusinessTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "RESTAURANT",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(7305),
                            IsDeleted = false,
                            Name = "Restaurant"
                        },
                        new
                        {
                            Id = 2,
                            Code = "CAFE",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(7318),
                            IsDeleted = false,
                            Name = "Cafe"
                        },
                        new
                        {
                            Id = 3,
                            Code = "BAKERY",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(7322),
                            IsDeleted = false,
                            Name = "Bakery"
                        },
                        new
                        {
                            Id = 4,
                            Code = "FAST_FOOD",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(7328),
                            IsDeleted = false,
                            Name = "Fast Food"
                        },
                        new
                        {
                            Id = 5,
                            Code = "HOTEL",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(7331),
                            IsDeleted = false,
                            Name = "Hotel"
                        },
                        new
                        {
                            Id = 6,
                            Code = "APARTMENT_RENTAL",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(7335),
                            IsDeleted = false,
                            Name = "Apartment Rental"
                        },
                        new
                        {
                            Id = 7,
                            Code = "TRAVEL_AGENCY",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(7338),
                            IsDeleted = false,
                            Name = "Travel Agency"
                        },
                        new
                        {
                            Id = 8,
                            Code = "TOUR_GUIDE",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(7342),
                            IsDeleted = false,
                            Name = "Tour Guide"
                        },
                        new
                        {
                            Id = 9,
                            Code = "CAR_RENTAL",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(7346),
                            IsDeleted = false,
                            Name = "Car Rental"
                        },
                        new
                        {
                            Id = 10,
                            Code = "AUTO_REPAIR",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(7350),
                            IsDeleted = false,
                            Name = "Auto Repair"
                        },
                        new
                        {
                            Id = 11,
                            Code = "CAR_DEALERSHIP",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(7353),
                            IsDeleted = false,
                            Name = "Car Dealership"
                        },
                        new
                        {
                            Id = 12,
                            Code = "TAXI_SERVICE",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(7357),
                            IsDeleted = false,
                            Name = "Taxi Service"
                        },
                        new
                        {
                            Id = 13,
                            Code = "MOVING_COMPANY",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(7360),
                            IsDeleted = false,
                            Name = "Moving Company"
                        },
                        new
                        {
                            Id = 14,
                            Code = "CONSTRUCTION_COMPANY",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(7364),
                            IsDeleted = false,
                            Name = "Construction Company"
                        },
                        new
                        {
                            Id = 15,
                            Code = "ARCHITECTURE_STUDIO",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(7367),
                            IsDeleted = false,
                            Name = "Architecture Studio"
                        },
                        new
                        {
                            Id = 16,
                            Code = "INTERIOR_DESIGN",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(7371),
                            IsDeleted = false,
                            Name = "Interior Design"
                        },
                        new
                        {
                            Id = 17,
                            Code = "REAL_ESTATE_AGENCY",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(7376),
                            IsDeleted = false,
                            Name = "Real Estate Agency"
                        },
                        new
                        {
                            Id = 18,
                            Code = "LAW_FIRM",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(7380),
                            IsDeleted = false,
                            Name = "Law Firm"
                        },
                        new
                        {
                            Id = 19,
                            Code = "ACCOUNTING_FIRM",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(7383),
                            IsDeleted = false,
                            Name = "Accounting Firm"
                        },
                        new
                        {
                            Id = 20,
                            Code = "INSURANCE_AGENCY",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(7387),
                            IsDeleted = false,
                            Name = "Insurance Agency"
                        },
                        new
                        {
                            Id = 21,
                            Code = "BANK",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(7392),
                            IsDeleted = false,
                            Name = "Bank"
                        },
                        new
                        {
                            Id = 22,
                            Code = "FINANCIAL_ADVISOR",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(7396),
                            IsDeleted = false,
                            Name = "Financial Advisor"
                        },
                        new
                        {
                            Id = 23,
                            Code = "MEDICAL_CLINIC",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(7401),
                            IsDeleted = false,
                            Name = "Medical Clinic"
                        },
                        new
                        {
                            Id = 24,
                            Code = "DENTAL_CLINIC",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(7406),
                            IsDeleted = false,
                            Name = "Dental Clinic"
                        },
                        new
                        {
                            Id = 25,
                            Code = "PHARMACY",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(7410),
                            IsDeleted = false,
                            Name = "Pharmacy"
                        },
                        new
                        {
                            Id = 26,
                            Code = "VETERINARY_CLINIC",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(7536),
                            IsDeleted = false,
                            Name = "Veterinary Clinic"
                        },
                        new
                        {
                            Id = 27,
                            Code = "FITNESS_GYM",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(7545),
                            IsDeleted = false,
                            Name = "Fitness Gym"
                        },
                        new
                        {
                            Id = 28,
                            Code = "PERSONAL_TRAINER",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(7549),
                            IsDeleted = false,
                            Name = "Personal Trainer"
                        },
                        new
                        {
                            Id = 29,
                            Code = "YOGA_STUDIO",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(7553),
                            IsDeleted = false,
                            Name = "Yoga Studio"
                        },
                        new
                        {
                            Id = 30,
                            Code = "BEAUTY_SALON",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(7559),
                            IsDeleted = false,
                            Name = "Beauty Salon"
                        },
                        new
                        {
                            Id = 31,
                            Code = "BARBER_SHOP",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(7563),
                            IsDeleted = false,
                            Name = "Barber Shop"
                        },
                        new
                        {
                            Id = 32,
                            Code = "SPA",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(7567),
                            IsDeleted = false,
                            Name = "Spa"
                        },
                        new
                        {
                            Id = 33,
                            Code = "TATTOO_STUDIO",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(7571),
                            IsDeleted = false,
                            Name = "Tattoo Studio"
                        },
                        new
                        {
                            Id = 34,
                            Code = "PHOTOGRAPHER",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(7574),
                            IsDeleted = false,
                            Name = "Photographer"
                        },
                        new
                        {
                            Id = 35,
                            Code = "VIDEOGRAPHER",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(7578),
                            IsDeleted = false,
                            Name = "Videographer"
                        },
                        new
                        {
                            Id = 36,
                            Code = "GRAPHIC_DESIGNER",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(7581),
                            IsDeleted = false,
                            Name = "Graphic Designer"
                        },
                        new
                        {
                            Id = 37,
                            Code = "WEB_DESIGN_AGENCY",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(7585),
                            IsDeleted = false,
                            Name = "Web Design Agency"
                        },
                        new
                        {
                            Id = 38,
                            Code = "SOFTWARE_COMPANY",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(8103),
                            IsDeleted = false,
                            Name = "Software Company"
                        },
                        new
                        {
                            Id = 39,
                            Code = "IT_SERVICES",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(8110),
                            IsDeleted = false,
                            Name = "IT Services"
                        },
                        new
                        {
                            Id = 40,
                            Code = "CYBERSECURITY_COMPANY",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(8113),
                            IsDeleted = false,
                            Name = "Cybersecurity Company"
                        },
                        new
                        {
                            Id = 41,
                            Code = "MARKETING_AGENCY",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(8118),
                            IsDeleted = false,
                            Name = "Marketing Agency"
                        },
                        new
                        {
                            Id = 42,
                            Code = "SEO_AGENCY",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(8121),
                            IsDeleted = false,
                            Name = "SEO Agency"
                        },
                        new
                        {
                            Id = 43,
                            Code = "DIGITAL_AGENCY",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(8127),
                            IsDeleted = false,
                            Name = "Digital Agency"
                        },
                        new
                        {
                            Id = 44,
                            Code = "FREELANCER",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(8131),
                            IsDeleted = false,
                            Name = "Freelancer"
                        },
                        new
                        {
                            Id = 45,
                            Code = "PORTFOLIO",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(8136),
                            IsDeleted = false,
                            Name = "Portfolio"
                        },
                        new
                        {
                            Id = 46,
                            Code = "PERSONAL_WEBSITE",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(8139),
                            IsDeleted = false,
                            Name = "Personal Website"
                        },
                        new
                        {
                            Id = 47,
                            Code = "BLOGGER",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(8143),
                            IsDeleted = false,
                            Name = "Blogger"
                        },
                        new
                        {
                            Id = 48,
                            Code = "INFLUENCER",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(8147),
                            IsDeleted = false,
                            Name = "Influencer"
                        },
                        new
                        {
                            Id = 49,
                            Code = "MUSICIAN",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(8150),
                            IsDeleted = false,
                            Name = "Musician"
                        },
                        new
                        {
                            Id = 50,
                            Code = "DJ",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(8154),
                            IsDeleted = false,
                            Name = "DJ"
                        });
                });

            modelBuilder.Entity("Domain.Entities.WebSiteBuilder.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "NAVBAR",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(6739),
                            IsDeleted = false,
                            Name = "Navbar"
                        },
                        new
                        {
                            Id = 2,
                            Code = "HERO",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(6823),
                            IsDeleted = false,
                            Name = "Hero"
                        },
                        new
                        {
                            Id = 3,
                            Code = "ABOUT",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(6829),
                            IsDeleted = false,
                            Name = "About"
                        },
                        new
                        {
                            Id = 4,
                            Code = "SERVICES",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(6832),
                            IsDeleted = false,
                            Name = "Services"
                        },
                        new
                        {
                            Id = 5,
                            Code = "FEATURES",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(6836),
                            IsDeleted = false,
                            Name = "Features"
                        },
                        new
                        {
                            Id = 6,
                            Code = "PORTFOLIO",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(6840),
                            IsDeleted = false,
                            Name = "Portfolio"
                        },
                        new
                        {
                            Id = 7,
                            Code = "GALLERY",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(6844),
                            IsDeleted = false,
                            Name = "Gallery"
                        },
                        new
                        {
                            Id = 8,
                            Code = "TESTIMONIALS",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(6849),
                            IsDeleted = false,
                            Name = "Testimonials"
                        },
                        new
                        {
                            Id = 9,
                            Code = "PRICING",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(6852),
                            IsDeleted = false,
                            Name = "Pricing"
                        },
                        new
                        {
                            Id = 10,
                            Code = "FAQ",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(6858),
                            IsDeleted = false,
                            Name = "FAQ"
                        },
                        new
                        {
                            Id = 11,
                            Code = "CONTACT",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(6863),
                            IsDeleted = false,
                            Name = "Contact"
                        },
                        new
                        {
                            Id = 12,
                            Code = "FOOTER",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(6866),
                            IsDeleted = false,
                            Name = "Footer"
                        },
                        new
                        {
                            Id = 13,
                            Code = "TEAM",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(6870),
                            IsDeleted = false,
                            Name = "Team"
                        },
                        new
                        {
                            Id = 14,
                            Code = "CLIENTS",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(6874),
                            IsDeleted = false,
                            Name = "Clients"
                        },
                        new
                        {
                            Id = 15,
                            Code = "STATISTICS",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(6878),
                            IsDeleted = false,
                            Name = "Statistics"
                        },
                        new
                        {
                            Id = 16,
                            Code = "SKILLS",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(6881),
                            IsDeleted = false,
                            Name = "Skills"
                        },
                        new
                        {
                            Id = 17,
                            Code = "EXPERIENCE",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(6886),
                            IsDeleted = false,
                            Name = "Experience"
                        },
                        new
                        {
                            Id = 18,
                            Code = "EDUCATION",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(6890),
                            IsDeleted = false,
                            Name = "Education"
                        },
                        new
                        {
                            Id = 19,
                            Code = "BLOG",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(6893),
                            IsDeleted = false,
                            Name = "Blog"
                        },
                        new
                        {
                            Id = 20,
                            Code = "NEWSLETTER",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(6897),
                            IsDeleted = false,
                            Name = "Newsletter"
                        },
                        new
                        {
                            Id = 21,
                            Code = "CTA",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(6900),
                            IsDeleted = false,
                            Name = "Call To Action"
                        },
                        new
                        {
                            Id = 22,
                            Code = "VIDEO",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(6904),
                            IsDeleted = false,
                            Name = "Video"
                        },
                        new
                        {
                            Id = 23,
                            Code = "PROCESS",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(6907),
                            IsDeleted = false,
                            Name = "Process"
                        },
                        new
                        {
                            Id = 24,
                            Code = "TECHNOLOGIES",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(6911),
                            IsDeleted = false,
                            Name = "Technologies"
                        },
                        new
                        {
                            Id = 25,
                            Code = "AWARDS",
                            CreatedDateTime = new DateTime(2026, 7, 15, 0, 15, 19, 214, DateTimeKind.Local).AddTicks(6914),
                            IsDeleted = false,
                            Name = "Awards"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Location.City", b =>
                {
                    b.HasOne("Domain.Entities.Location.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Domain.Entities.Location.Region", b =>
                {
                    b.HasOne("Domain.Entities.Location.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Domain.Entities.Personal.UserContact", b =>
                {
                    b.HasOne("Domain.Entities.Personal.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Personal.UserSettings", b =>
                {
                    b.HasOne("Domain.Entities.System.Settings", "Settings")
                        .WithMany()
                        .HasForeignKey("SettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Personal.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Settings");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.System.Feedback", b =>
                {
                    b.HasOne("Domain.Entities.Personal.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.System.MessageUs", b =>
                {
                    b.HasOne("Domain.Entities.System.MessageUsReason", "MessageUsReason")
                        .WithMany()
                        .HasForeignKey("MessageUsReasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MessageUsReason");
                });
#pragma warning restore 612, 618
        }
    }
}
