using Domain.Entities.Location;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.Emit;
using System.Text;
using System.Threading.Tasks;

namespace Core.EF.Seed
{
    public static class CountriesDatabaseSeed
    {
        public static void Seed(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Country>().HasData(
                new Country { Id = 1, Name = "Afghanistan", Iso = "AF" },
                new Country { Id = 2, Name = "Albania", Iso = "AL" },
                new Country { Id = 3, Name = "Algeria", Iso = "DZ" },
                new Country { Id = 4, Name = "Andorra", Iso = "AD" },
                new Country { Id = 5, Name = "Angola", Iso = "AO" },
                new Country { Id = 6, Name = "Antigua and Barbuda", Iso = "AG" },
                new Country { Id = 7, Name = "Argentina", Iso = "AR" },
                new Country { Id = 8, Name = "Armenia", Iso = "AM" },
                new Country { Id = 9, Name = "Australia", Iso = "AU" },
                new Country { Id = 10, Name = "Austria", Iso = "AT" },
                new Country { Id = 11, Name = "Azerbaijan", Iso = "AZ" },
                new Country { Id = 12, Name = "Bahamas", Iso = "BS" },
                new Country { Id = 13, Name = "Bahrain", Iso = "BH" },
                new Country { Id = 14, Name = "Bangladesh", Iso = "BD" },
                new Country { Id = 15, Name = "Barbados", Iso = "BB" },
                new Country { Id = 16, Name = "Belarus", Iso = "BY" },
                new Country { Id = 17, Name = "Belgium", Iso = "BE" },
                new Country { Id = 18, Name = "Belize", Iso = "BZ" },
                new Country { Id = 19, Name = "Benin", Iso = "BJ" },
                new Country { Id = 20, Name = "Bhutan", Iso = "BT" },
                new Country { Id = 21, Name = "Bolivia", Iso = "BO" },
                new Country { Id = 22, Name = "Bosnia and Herzegovina", Iso = "BA" },
                new Country { Id = 23, Name = "Botswana", Iso = "BW" },
                new Country { Id = 24, Name = "Brazil", Iso = "BR" },
                new Country { Id = 25, Name = "Brunei Darussalam", Iso = "BN" },
                new Country { Id = 26, Name = "Bulgaria", Iso = "BG" },
                new Country { Id = 27, Name = "Burkina Faso", Iso = "BF" },
                new Country { Id = 28, Name = "Burundi", Iso = "BI" },
                new Country { Id = 29, Name = "Cabo Verde", Iso = "CV" },
                new Country { Id = 30, Name = "Cambodia", Iso = "KH" },
                new Country { Id = 31, Name = "Cameroon", Iso = "CM" },
                new Country { Id = 32, Name = "Canada", Iso = "CA" },
                new Country { Id = 33, Name = "Central African Republic", Iso = "CF" },
                new Country { Id = 34, Name = "Chad", Iso = "TD" },
                new Country { Id = 35, Name = "Chile", Iso = "CL" },
                new Country { Id = 36, Name = "China", Iso = "CN" },
                new Country { Id = 37, Name = "Colombia", Iso = "CO" },
                new Country { Id = 38, Name = "Comoros", Iso = "KM" },
                new Country { Id = 39, Name = "Congo", Iso = "CG" },
                new Country { Id = 40, Name = "Congo (Democratic Republic)", Iso = "CD" },
                new Country { Id = 41, Name = "Costa Rica", Iso = "CR" },
                new Country { Id = 42, Name = "Croatia", Iso = "HR" },
                new Country { Id = 43, Name = "Cuba", Iso = "CU" },
                new Country { Id = 44, Name = "Cyprus", Iso = "CY" },
                new Country { Id = 45, Name = "Czech Republic", Iso = "CZ" },
                new Country { Id = 46, Name = "Denmark", Iso = "DK" },
                new Country { Id = 47, Name = "Djibouti", Iso = "DJ" },
                new Country { Id = 48, Name = "Dominica", Iso = "DM" },
                new Country { Id = 49, Name = "Dominican Republic", Iso = "DO" },
                new Country { Id = 50, Name = "Ecuador", Iso = "EC" },
                new Country { Id = 51, Name = "Egypt", Iso = "EG" },
                new Country { Id = 52, Name = "El Salvador", Iso = "SV" },
                new Country { Id = 53, Name = "Equatorial Guinea", Iso = "GQ" },
                new Country { Id = 54, Name = "Eritrea", Iso = "ER" },
                new Country { Id = 55, Name = "Estonia", Iso = "EE" },
                new Country { Id = 56, Name = "Eswatini", Iso = "SZ" },
                new Country { Id = 57, Name = "Ethiopia", Iso = "ET" },
                new Country { Id = 58, Name = "Fiji", Iso = "FJ" },
                new Country { Id = 59, Name = "Finland", Iso = "FI" },
                new Country { Id = 60, Name = "France", Iso = "FR" },
                new Country { Id = 61, Name = "Gabon", Iso = "GA" },
                new Country { Id = 62, Name = "Gambia", Iso = "GM" },
                new Country { Id = 63, Name = "Georgia", Iso = "GE" },
                new Country { Id = 64, Name = "Germany", Iso = "DE" },
                new Country { Id = 65, Name = "Ghana", Iso = "GH" },
                new Country { Id = 66, Name = "Greece", Iso = "GR" },
                new Country { Id = 67, Name = "Grenada", Iso = "GD" },
                new Country { Id = 68, Name = "Guatemala", Iso = "GT" },
                new Country { Id = 69, Name = "Guinea", Iso = "GN" },
                new Country { Id = 70, Name = "Guinea-Bissau", Iso = "GW" },
                new Country { Id = 71, Name = "Guyana", Iso = "GY" },
                new Country { Id = 72, Name = "Haiti", Iso = "HT" },
                new Country { Id = 73, Name = "Honduras", Iso = "HN" },
                new Country { Id = 74, Name = "Hungary", Iso = "HU" },
                new Country { Id = 75, Name = "Iceland", Iso = "IS" },
                new Country { Id = 76, Name = "India", Iso = "IN" },
                new Country { Id = 77, Name = "Indonesia", Iso = "ID" },
                new Country { Id = 78, Name = "Iran", Iso = "IR" },
                new Country { Id = 79, Name = "Iraq", Iso = "IQ" },
                new Country { Id = 80, Name = "Ireland", Iso = "IE" },
                new Country { Id = 81, Name = "Israel", Iso = "IL" },
                new Country { Id = 82, Name = "Italy", Iso = "IT" },
                new Country { Id = 83, Name = "Jamaica", Iso = "JM" },
                new Country { Id = 84, Name = "Japan", Iso = "JP" },
                new Country { Id = 85, Name = "Jordan", Iso = "JO" },
                new Country { Id = 86, Name = "Kazakhstan", Iso = "KZ" },
                new Country { Id = 87, Name = "Kenya", Iso = "KE" },
                new Country { Id = 88, Name = "Kiribati", Iso = "KI" },
                new Country { Id = 89, Name = "Korea (North)", Iso = "KP" },
                new Country { Id = 90, Name = "Korea (South)", Iso = "KR" },
                new Country { Id = 91, Name = "Kuwait", Iso = "KW" },
                new Country { Id = 92, Name = "Kyrgyzstan", Iso = "KG" },
                new Country { Id = 93, Name = "Laos", Iso = "LA" },
                new Country { Id = 94, Name = "Latvia", Iso = "LV" },
                new Country { Id = 95, Name = "Lebanon", Iso = "LB" },
                new Country { Id = 96, Name = "Lesotho", Iso = "LS" },
                new Country { Id = 97, Name = "Liberia", Iso = "LR" },
                new Country { Id = 98, Name = "Libya", Iso = "LY" },
                new Country { Id = 99, Name = "Liechtenstein", Iso = "LI" },
                new Country { Id = 100, Name = "Lithuania", Iso = "LT" },
                new Country { Id = 101, Name = "Luxembourg", Iso = "LU" },
                new Country { Id = 102, Name = "Madagascar", Iso = "MG" },
                new Country { Id = 103, Name = "Malawi", Iso = "MW" },
                new Country { Id = 104, Name = "Malaysia", Iso = "MY" },
                new Country { Id = 105, Name = "Maldives", Iso = "MV" },
                new Country { Id = 106, Name = "Mali", Iso = "ML" },
                new Country { Id = 107, Name = "Malta", Iso = "MT" },
                new Country { Id = 108, Name = "Marshall Islands", Iso = "MH" },
                new Country { Id = 109, Name = "Mauritania", Iso = "MR" },
                new Country { Id = 110, Name = "Mauritius", Iso = "MU" },
                new Country { Id = 111, Name = "Mexico", Iso = "MX" },
                new Country { Id = 112, Name = "Micronesia", Iso = "FM" },
                new Country { Id = 113, Name = "Moldova", Iso = "MD" },
                new Country { Id = 114, Name = "Monaco", Iso = "MC" },
                new Country { Id = 115, Name = "Mongolia", Iso = "MN" },
                new Country { Id = 116, Name = "Montenegro", Iso = "ME" },
                new Country { Id = 117, Name = "Morocco", Iso = "MA" },
                new Country { Id = 118, Name = "Mozambique", Iso = "MZ" },
                new Country { Id = 119, Name = "Myanmar", Iso = "MM" },
                new Country { Id = 120, Name = "Namibia", Iso = "NA" },
                new Country { Id = 121, Name = "Nauru", Iso = "NR" },
                new Country { Id = 122, Name = "Nepal", Iso = "NP" },
                new Country { Id = 123, Name = "Netherlands", Iso = "NL" },
                new Country { Id = 124, Name = "New Zealand", Iso = "NZ" },
                new Country { Id = 125, Name = "Nicaragua", Iso = "NI" },
                new Country { Id = 126, Name = "Niger", Iso = "NE" },
                new Country { Id = 127, Name = "Nigeria", Iso = "NG" },
                new Country { Id = 128, Name = "North Macedonia", Iso = "MK" },
                new Country { Id = 129, Name = "Norway", Iso = "NO" },
                new Country { Id = 130, Name = "Oman", Iso = "OM" },
                new Country { Id = 131, Name = "Pakistan", Iso = "PK" },
                new Country { Id = 132, Name = "Palau", Iso = "PW" },
                new Country { Id = 133, Name = "Panama", Iso = "PA" },
                new Country { Id = 134, Name = "Papua New Guinea", Iso = "PG" },
                new Country { Id = 135, Name = "Paraguay", Iso = "PY" },
                new Country { Id = 136, Name = "Peru", Iso = "PE" },
                new Country { Id = 137, Name = "Philippines", Iso = "PH" },
                new Country { Id = 138, Name = "Poland", Iso = "PL" },
                new Country { Id = 139, Name = "Portugal", Iso = "PT" },
                new Country { Id = 140, Name = "Qatar", Iso = "QA" },
                new Country { Id = 141, Name = "Romania", Iso = "RO" },
                new Country { Id = 142, Name = "Russia", Iso = "RU" },
                new Country { Id = 143, Name = "Rwanda", Iso = "RW" },
                new Country { Id = 144, Name = "Saint Kitts and Nevis", Iso = "KN" },
                new Country { Id = 145, Name = "Saint Lucia", Iso = "LC" },
                new Country { Id = 146, Name = "Saint Vincent and the Grenadines", Iso = "VC" },
                new Country { Id = 147, Name = "Samoa", Iso = "WS" },
                new Country { Id = 148, Name = "San Marino", Iso = "SM" },
                new Country { Id = 149, Name = "Sao Tome and Principe", Iso = "ST" },
                new Country { Id = 150, Name = "Saudi Arabia", Iso = "SA" },
                new Country { Id = 151, Name = "Senegal", Iso = "SN" },
                new Country { Id = 152, Name = "Serbia", Iso = "RS" },
                new Country { Id = 153, Name = "Seychelles", Iso = "SC" },
                new Country { Id = 154, Name = "Sierra Leone", Iso = "SL" },
                new Country { Id = 155, Name = "Singapore", Iso = "SG" },
                new Country { Id = 156, Name = "Slovakia", Iso = "SK" },
                new Country { Id = 157, Name = "Slovenia", Iso = "SI" },
                new Country { Id = 158, Name = "Solomon Islands", Iso = "SB" },
                new Country { Id = 159, Name = "Somalia", Iso = "SO" },
                new Country { Id = 160, Name = "South Africa", Iso = "ZA" },
                new Country { Id = 161, Name = "South Sudan", Iso = "SS" },
                new Country { Id = 162, Name = "Spain", Iso = "ES" },
                new Country { Id = 163, Name = "Sri Lanka", Iso = "LK" },
                new Country { Id = 164, Name = "Sudan", Iso = "SD" },
                new Country { Id = 165, Name = "Suriname", Iso = "SR" },
                new Country { Id = 166, Name = "Sweden", Iso = "SE" },
                new Country { Id = 167, Name = "Switzerland", Iso = "CH" },
                new Country { Id = 168, Name = "Syria", Iso = "SY" },
                new Country { Id = 169, Name = "Taiwan", Iso = "TW" },
                new Country { Id = 170, Name = "Tajikistan", Iso = "TJ" },
                new Country { Id = 171, Name = "Tanzania", Iso = "TZ" },
                new Country { Id = 172, Name = "Thailand", Iso = "TH" },
                new Country { Id = 173, Name = "Timor-Leste", Iso = "TL" },
                new Country { Id = 174, Name = "Togo", Iso = "TG" },
                new Country { Id = 175, Name = "Tonga", Iso = "TO" },
                new Country { Id = 176, Name = "Trinidad and Tobago", Iso = "TT" },
                new Country { Id = 177, Name = "Tunisia", Iso = "TN" },
                new Country { Id = 178, Name = "Turkey", Iso = "TR" },
                new Country { Id = 179, Name = "Turkmenistan", Iso = "TM" },
                new Country { Id = 180, Name = "Tuvalu", Iso = "TV" },
                new Country { Id = 181, Name = "Uganda", Iso = "UG" },
                new Country { Id = 182, Name = "Ukraine", Iso = "UA" },
                new Country { Id = 183, Name = "United Arab Emirates", Iso = "AE" },
                new Country { Id = 184, Name = "United Kingdom", Iso = "GB" },
                new Country { Id = 185, Name = "United States", Iso = "US" },
                new Country { Id = 186, Name = "Uruguay", Iso = "UY" },
                new Country { Id = 187, Name = "Uzbekistan", Iso = "UZ" },
                new Country { Id = 188, Name = "Vanuatu", Iso = "VU" },
                new Country { Id = 189, Name = "Vatican City", Iso = "VA" },
                new Country { Id = 190, Name = "Venezuela", Iso = "VE" },
                new Country { Id = 191, Name = "Vietnam", Iso = "VN" },
                new Country { Id = 192, Name = "Yemen", Iso = "YE" },
                new Country { Id = 193, Name = "Zambia", Iso = "ZM" },
                new Country { Id = 194, Name = "Zimbabwe", Iso = "ZW" },
                new Country { Id = 195, Name = "Palestine", Iso = "PS" },
                new Country { Id = 196, Name = "Kosovo", Iso = "XK" },
                new Country { Id = 197, Name = "Cook Islands", Iso = "CK" },
                new Country { Id = 198, Name = "Curacao", Iso = "CW" },
                new Country { Id = 199, Name = "Ivory coast", Iso = "CI" },
                new Country { Id = 200, Name = "Reunion (France)", Iso = "RE" }

            );
        } 
    }
}
